export const moviedata =[
    {
        name :"the conjuring",
        time :"112 min",
        directedby:"James Wan",
        producedby:"Peter Safran,Rob Cowan,Tony DeRosa-Grund",
        pic:"https://m.media-amazon.com/images/I/91Jo6zE35BL._AC_UF1000,1000_QL80_.jpg",
        type:"horror",
    },
    {
        name :"baby driver",
        time :"118min",
        directedby:"Edgar Wright",
        producedby:"Jon Hamm ,Edgar Wright ",
        pic:"https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p13259415_v_v12_au.jpg",
        type:"action",
    },
    {
        name :"american psycho",
        time :"150min",
        directedby:"Mary Harron",
        producedby:"Chris Hanley ,Edward R. Pressman,Ernie Barbarash",
        pic:"https://m.media-amazon.com/images/S/pv-target-images/473a226898cf184df3ca599f76ea789923e08cd74825239225b2cfd579daa582.jpg",
        type:"horror",
    },
    {
        name :"jhon wick",
        time :"119min",
        directedby:"Chad Stahelski",
        producedby:"David Leitch,Eva Longoria,Basil Iwanyk",
        pic:"https://fr.web.img4.acsta.net/pictures/14/10/08/11/49/255061.jpg",
        type:"action",
    },
    {
        name :"oppenheimer",
        time :"210min",
        directedby:"Christopher Nolan",
        producedby:"Charles Roven,Christopher Nolan,Emma Thomas",
        pic:"https://focus.courrierinternational.com/2023/07/13/0/0/1087/800/1280/0/60/0/91467a9_1689250399651-oppenheimer-murphy.jpeg",
        type:"action",
    },
]